## Random Sampling 

In [1]:
import numpy as np
import random

In [2]:
np.random.random(1)

array([0.13850782])

In [3]:
np.random.random((3,3))

array([[0.53042107, 0.86329127, 0.23630516],
       [0.97470246, 0.66791423, 0.82099397],
       [0.82880985, 0.98375176, 0.0941061 ]])

In [4]:
 np.random.randint(1,4)

1

In [5]:
 np.random.randint(1,4,(4,4))

array([[2, 3, 2, 2],
       [3, 3, 1, 1],
       [1, 1, 3, 3],
       [2, 3, 1, 3]])

In [6]:
np.random.randint(1,4,(2,4,4))

array([[[1, 2, 2, 2],
        [2, 3, 1, 3],
        [2, 2, 3, 1],
        [1, 3, 2, 2]],

       [[3, 1, 1, 2],
        [1, 3, 2, 1],
        [2, 2, 3, 1],
        [1, 3, 2, 2]]])

In [7]:
np.random.seed(10)
np.random.randint(1,4,(2,4,4))

array([[[2, 2, 1, 1],
        [2, 1, 2, 2],
        [1, 2, 2, 3],
        [1, 2, 1, 3]],

       [[1, 3, 1, 1],
        [1, 3, 1, 3],
        [3, 2, 1, 1],
        [3, 2, 3, 2]]])

In [8]:
np.random.seed(10)
np.random.randint(1,4,(2,4,4))

array([[[2, 2, 1, 1],
        [2, 1, 2, 2],
        [1, 2, 2, 3],
        [1, 2, 1, 3]],

       [[1, 3, 1, 1],
        [1, 3, 1, 3],
        [3, 2, 1, 1],
        [3, 2, 3, 2]]])

In [9]:
np.random.seed(10)
np.random.randint(1,4,(3,3))

array([[2, 2, 1],
       [1, 2, 1],
       [2, 2, 1]])

In [10]:
np.random.rand(3)

array([0.02517173, 0.70920801, 0.26556613])

In [11]:
np.random.rand(3,3)

array([[0.26360285, 0.15037787, 0.68381843],
       [0.81660184, 0.33607158, 0.89081653],
       [0.19812181, 0.03061665, 0.87761494]])

In [12]:
np.random.randn(3,3)

array([[ 0.31085074,  1.72937588, -0.24066194],
       [-1.02735202,  0.42401507,  1.40862087],
       [ 0.43999202, -0.42823439, -0.31201268]])

In [13]:
x = [1,2,3,4,5,6]
np.random.choice(x)

4

In [14]:
np.random.choice(x)

3

In [15]:
np.random.choice(x)

6

In [16]:
np.random.permutation(x)

array([2, 3, 5, 4, 1, 6])

In [17]:
np.random.permutation(x)

array([5, 6, 3, 4, 2, 1])

In [18]:
np.random.permutation(x)

array([6, 5, 3, 2, 4, 1])